// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: mj.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PackageID int32

const (
	PackageID_PID_INVALID          PackageID = 0
	PackageID_PID_USER_LOGIN_REQ   PackageID = 1
	PackageID_PID_USER_LOGIN_RSP   PackageID = 2
	PackageID_PID_CREATE_TABLE_REQ PackageID = 3
	PackageID_PID_CREATE_TABLE_RSP PackageID = 4
	PackageID_PID_SEARCH_TABLE_REQ PackageID = 5
	PackageID_PID_SEARCH_TABLE_RSP PackageID = 6
)

// Enum value maps for PackageID.
var (
	PackageID_name = map[int32]string{
		0: "PID_INVALID",
		1: "PID_USER_LOGIN_REQ",
		2: "PID_USER_LOGIN_RSP",
		3: "PID_CREATE_TABLE_REQ",
		4: "PID_CREATE_TABLE_RSP",
		5: "PID_SEARCH_TABLE_REQ",
		6: "PID_SEARCH_TABLE_RSP",
	}
	PackageID_value = map[string]int32{
		"PID_INVALID":          0,
		"PID_USER_LOGIN_REQ":   1,
		"PID_USER_LOGIN_RSP":   2,
		"PID_CREATE_TABLE_REQ": 3,
		"PID_CREATE_TABLE_RSP": 4,
		"PID_SEARCH_TABLE_REQ": 5,
		"PID_SEARCH_TABLE_RSP": 6,
	}
)

func (x PackageID) Enum() *PackageID {
	p := new(PackageID)
	*p = x
	return p
}

func (x PackageID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PackageID) Descriptor() protoreflect.EnumDescriptor {
	return file_mj_proto_enumTypes[0].Descriptor()
}

func (PackageID) Type() protoreflect.EnumType {
	return &file_mj_proto_enumTypes[0]
}

func (x PackageID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PackageID.Descriptor instead.
func (PackageID) EnumDescriptor() ([]byte, []int) {
	return file_mj_proto_rawDescGZIP(), []int{0}
}

type UserInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID string  `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Score  float64 `protobuf:"fixed64,2,opt,name=Score,proto3" json:"Score,omitempty"`
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mj_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_mj_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_mj_proto_rawDescGZIP(), []int{0}
}

func (x *UserInfo) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *UserInfo) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type TableInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID       string  `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	MaxRound     int32   `protobuf:"varint,2,opt,name=MaxRound,proto3" json:"MaxRound,omitempty"`
	BaseScore    float64 `protobuf:"fixed64,3,opt,name=BaseScore,proto3" json:"BaseScore,omitempty"`
	MaxFan       int32   `protobuf:"varint,4,opt,name=MaxFan,proto3" json:"MaxFan,omitempty"`
	CurrentRound int32   `protobuf:"varint,5,opt,name=CurrentRound,proto3" json:"CurrentRound,omitempty"`
}

func (x *TableInfo) Reset() {
	*x = TableInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mj_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TableInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableInfo) ProtoMessage() {}

func (x *TableInfo) ProtoReflect() protoreflect.Message {
	mi := &file_mj_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableInfo.ProtoReflect.Descriptor instead.
func (*TableInfo) Descriptor() ([]byte, []int) {
	return file_mj_proto_rawDescGZIP(), []int{1}
}

func (x *TableInfo) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *TableInfo) GetMaxRound() int32 {
	if x != nil {
		return x.MaxRound
	}
	return 0
}

func (x *TableInfo) GetBaseScore() float64 {
	if x != nil {
		return x.BaseScore
	}
	return 0
}

func (x *TableInfo) GetMaxFan() int32 {
	if x != nil {
		return x.MaxFan
	}
	return 0
}

func (x *TableInfo) GetCurrentRound() int32 {
	if x != nil {
		return x.CurrentRound
	}
	return 0
}

type Package struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PID        PackageID `protobuf:"varint,1,opt,name=PID,proto3,enum=pb.PackageID" json:"PID,omitempty"`
	Idempotent int64     `protobuf:"varint,2,opt,name=Idempotent,proto3" json:"Idempotent,omitempty"`
	Data       []byte    `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *Package) Reset() {
	*x = Package{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mj_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Package) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Package) ProtoMessage() {}

func (x *Package) ProtoReflect() protoreflect.Message {
	mi := &file_mj_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Package.ProtoReflect.Descriptor instead.
func (*Package) Descriptor() ([]byte, []int) {
	return file_mj_proto_rawDescGZIP(), []int{2}
}

func (x *Package) GetPID() PackageID {
	if x != nil {
		return x.PID
	}
	return PackageID_PID_INVALID
}

func (x *Package) GetIdempotent() int64 {
	if x != nil {
		return x.Idempotent
	}
	return 0
}

func (x *Package) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UserLoginReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID string `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
}

func (x *UserLoginReq) Reset() {
	*x = UserLoginReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mj_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLoginReq) ProtoMessage() {}

func (x *UserLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_mj_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLoginReq.ProtoReflect.Descriptor instead.
func (*UserLoginReq) Descriptor() ([]byte, []int) {
	return file_mj_proto_rawDescGZIP(), []int{3}
}

func (x *UserLoginReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type UserLoginRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code     int32     `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Error    string    `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	UserInfo *UserInfo `protobuf:"bytes,3,opt,name=UserInfo,proto3" json:"UserInfo,omitempty"`
}

func (x *UserLoginRsp) Reset() {
	*x = UserLoginRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mj_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserLoginRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLoginRsp) ProtoMessage() {}

func (x *UserLoginRsp) ProtoReflect() protoreflect.Message {
	mi := &file_mj_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLoginRsp.ProtoReflect.Descriptor instead.
func (*UserLoginRsp) Descriptor() ([]byte, []int) {
	return file_mj_proto_rawDescGZIP(), []int{4}
}

func (x *UserLoginRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UserLoginRsp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *UserLoginRsp) GetUserInfo() *UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

type CreateTableReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID    string  `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`         // 属性用户
	MaxRound  int32   `protobuf:"varint,2,opt,name=MaxRound,proto3" json:"MaxRound,omitempty"`    // 局数
	BaseScore float64 `protobuf:"fixed64,3,opt,name=BaseScore,proto3" json:"BaseScore,omitempty"` // 底分
	MaxFan    int32   `protobuf:"varint,4,opt,name=MaxFan,proto3" json:"MaxFan,omitempty"`        // 最大番
}

func (x *CreateTableReq) Reset() {
	*x = CreateTableReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mj_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTableReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTableReq) ProtoMessage() {}

func (x *CreateTableReq) ProtoReflect() protoreflect.Message {
	mi := &file_mj_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTableReq.ProtoReflect.Descriptor instead.
func (*CreateTableReq) Descriptor() ([]byte, []int) {
	return file_mj_proto_rawDescGZIP(), []int{5}
}

func (x *CreateTableReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *CreateTableReq) GetMaxRound() int32 {
	if x != nil {
		return x.MaxRound
	}
	return 0
}

func (x *CreateTableReq) GetBaseScore() float64 {
	if x != nil {
		return x.BaseScore
	}
	return 0
}

func (x *CreateTableReq) GetMaxFan() int32 {
	if x != nil {
		return x.MaxFan
	}
	return 0
}

type CreateTableRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Error   string `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	TableID int32  `protobuf:"varint,3,opt,name=TableID,proto3" json:"TableID,omitempty"`
}

func (x *CreateTableRsp) Reset() {
	*x = CreateTableRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mj_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTableRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTableRsp) ProtoMessage() {}

func (x *CreateTableRsp) ProtoReflect() protoreflect.Message {
	mi := &file_mj_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTableRsp.ProtoReflect.Descriptor instead.
func (*CreateTableRsp) Descriptor() ([]byte, []int) {
	return file_mj_proto_rawDescGZIP(), []int{6}
}

func (x *CreateTableRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateTableRsp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CreateTableRsp) GetTableID() int32 {
	if x != nil {
		return x.TableID
	}
	return 0
}

type SearchTableReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableID int32 `protobuf:"varint,1,opt,name=TableID,proto3" json:"TableID,omitempty"`
}

func (x *SearchTableReq) Reset() {
	*x = SearchTableReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mj_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchTableReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTableReq) ProtoMessage() {}

func (x *SearchTableReq) ProtoReflect() protoreflect.Message {
	mi := &file_mj_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTableReq.ProtoReflect.Descriptor instead.
func (*SearchTableReq) Descriptor() ([]byte, []int) {
	return file_mj_proto_rawDescGZIP(), []int{7}
}

func (x *SearchTableReq) GetTableID() int32 {
	if x != nil {
		return x.TableID
	}
	return 0
}

type SearchTableRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SearchTableRsp) Reset() {
	*x = SearchTableRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mj_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchTableRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTableRsp) ProtoMessage() {}

func (x *SearchTableRsp) ProtoReflect() protoreflect.Message {
	mi := &file_mj_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTableRsp.ProtoReflect.Descriptor instead.
func (*SearchTableRsp) Descriptor() ([]byte, []int) {
	return file_mj_proto_rawDescGZIP(), []int{8}
}

var File_mj_proto protoreflect.FileDescriptor

var file_mj_proto_rawDesc = []byte{
	0x0a, 0x08, 0x6d, 0x6a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x38,
	0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x05, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x22, 0x99, 0x01, 0x0a, 0x09, 0x54, 0x61, 0x62,
	0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a,
	0x0a, 0x08, 0x4d, 0x61, 0x78, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x4d, 0x61, 0x78, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x42, 0x61,
	0x73, 0x65, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x42,
	0x61, 0x73, 0x65, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x4d, 0x61, 0x78, 0x46,
	0x61, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x4d, 0x61, 0x78, 0x46, 0x61, 0x6e,
	0x12, 0x22, 0x0a, 0x0c, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x52, 0x6f, 0x75, 0x6e, 0x64,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x52,
	0x6f, 0x75, 0x6e, 0x64, 0x22, 0x5e, 0x0a, 0x07, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x12,
	0x1f, 0x0a, 0x03, 0x50, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x70,
	0x62, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x49, 0x44, 0x52, 0x03, 0x50, 0x49, 0x44,
	0x12, 0x1e, 0x0a, 0x0a, 0x49, 0x64, 0x65, 0x6d, 0x70, 0x6f, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x49, 0x64, 0x65, 0x6d, 0x70, 0x6f, 0x74, 0x65, 0x6e, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x44, 0x61, 0x74, 0x61, 0x22, 0x26, 0x0a, 0x0c, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x22, 0x62, 0x0a, 0x0c,
	0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04,
	0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x28, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x22, 0x7a, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52,
	0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x4d, 0x61,
	0x78, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x4d, 0x61,
	0x78, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x42, 0x61, 0x73, 0x65, 0x53, 0x63,
	0x6f, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x42, 0x61, 0x73, 0x65, 0x53,
	0x63, 0x6f, 0x72, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x4d, 0x61, 0x78, 0x46, 0x61, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x4d, 0x61, 0x78, 0x46, 0x61, 0x6e, 0x22, 0x54, 0x0a, 0x0e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x73, 0x70, 0x12, 0x12,
	0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x54, 0x61, 0x62, 0x6c,
	0x65, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x54, 0x61, 0x62, 0x6c, 0x65,
	0x49, 0x44, 0x22, 0x2a, 0x0a, 0x0e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x54, 0x61, 0x62, 0x6c,
	0x65, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x44, 0x22, 0x10,
	0x0a, 0x0e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x73, 0x70,
	0x2a, 0xb4, 0x01, 0x0a, 0x09, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x49, 0x44, 0x12, 0x0f,
	0x0a, 0x0b, 0x50, 0x49, 0x44, 0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x00, 0x12,
	0x16, 0x0a, 0x12, 0x50, 0x49, 0x44, 0x5f, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x4c, 0x4f, 0x47, 0x49,
	0x4e, 0x5f, 0x52, 0x45, 0x51, 0x10, 0x01, 0x12, 0x16, 0x0a, 0x12, 0x50, 0x49, 0x44, 0x5f, 0x55,
	0x53, 0x45, 0x52, 0x5f, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x5f, 0x52, 0x53, 0x50, 0x10, 0x02, 0x12,
	0x18, 0x0a, 0x14, 0x50, 0x49, 0x44, 0x5f, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x5f, 0x54, 0x41,
	0x42, 0x4c, 0x45, 0x5f, 0x52, 0x45, 0x51, 0x10, 0x03, 0x12, 0x18, 0x0a, 0x14, 0x50, 0x49, 0x44,
	0x5f, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x5f, 0x54, 0x41, 0x42, 0x4c, 0x45, 0x5f, 0x52, 0x53,
	0x50, 0x10, 0x04, 0x12, 0x18, 0x0a, 0x14, 0x50, 0x49, 0x44, 0x5f, 0x53, 0x45, 0x41, 0x52, 0x43,
	0x48, 0x5f, 0x54, 0x41, 0x42, 0x4c, 0x45, 0x5f, 0x52, 0x45, 0x51, 0x10, 0x05, 0x12, 0x18, 0x0a,
	0x14, 0x50, 0x49, 0x44, 0x5f, 0x53, 0x45, 0x41, 0x52, 0x43, 0x48, 0x5f, 0x54, 0x41, 0x42, 0x4c,
	0x45, 0x5f, 0x52, 0x53, 0x50, 0x10, 0x06, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2e, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mj_proto_rawDescOnce sync.Once
	file_mj_proto_rawDescData = file_mj_proto_rawDesc
)

func file_mj_proto_rawDescGZIP() []byte {
	file_mj_proto_rawDescOnce.Do(func() {
		file_mj_proto_rawDescData = protoimpl.X.CompressGZIP(file_mj_proto_rawDescData)
	})
	return file_mj_proto_rawDescData
}

var file_mj_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mj_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_mj_proto_goTypes = []interface{}{
	(PackageID)(0),         // 0: pb.PackageID
	(*UserInfo)(nil),       // 1: pb.UserInfo
	(*TableInfo)(nil),      // 2: pb.TableInfo
	(*Package)(nil),        // 3: pb.Package
	(*UserLoginReq)(nil),   // 4: pb.UserLoginReq
	(*UserLoginRsp)(nil),   // 5: pb.UserLoginRsp
	(*CreateTableReq)(nil), // 6: pb.CreateTableReq
	(*CreateTableRsp)(nil), // 7: pb.CreateTableRsp
	(*SearchTableReq)(nil), // 8: pb.SearchTableReq
	(*SearchTableRsp)(nil), // 9: pb.SearchTableRsp
}
var file_mj_proto_depIdxs = []int32{
	0, // 0: pb.Package.PID:type_name -> pb.PackageID
	1, // 1: pb.UserLoginRsp.UserInfo:type_name -> pb.UserInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_mj_proto_init() }
func file_mj_proto_init() {
	if File_mj_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mj_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mj_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TableInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mj_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Package); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mj_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserLoginReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mj_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserLoginRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mj_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTableReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mj_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTableRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mj_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchTableReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mj_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchTableRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mj_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mj_proto_goTypes,
		DependencyIndexes: file_mj_proto_depIdxs,
		EnumInfos:         file_mj_proto_enumTypes,
		MessageInfos:      file_mj_proto_msgTypes,
	}.Build()
	File_mj_proto = out.File
	file_mj_proto_rawDesc = nil
	file_mj_proto_goTypes = nil
	file_mj_proto_depIdxs = nil
}
